# Generated by Django 4.0 on 2022-05-17 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar_num',
            field=models.PositiveIntegerField(max_length=12, primary_key='True', serialize=False, validators=[django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6, primary_key='True', serialize=False, validators=[django.core.validators.RegexValidator(regex='^d{6}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_num',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='job_role',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institute',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='percentage',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
