# Generated by Django 4.0 on 2022-05-17 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_address_id_alter_aadhar_aadhar_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar_num',
            field=models.PositiveIntegerField(primary_key='True', serialize=False, validators=[django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^d{6}$')]),
        ),
    ]
