# Generated by Django 4.0 on 2022-05-18 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1950)]),
        ),
    ]
