# Generated by Django 4.0 on 2022-05-17 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_id_alter_aadhar_aadhar_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar_num',
            field=models.CharField(max_length=12, primary_key='True', serialize=False, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_num',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
