# Generated by Django 4.0 on 2022-05-17 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_aadhar_aadhar_num_alter_address_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_num',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(16)]),
        ),
    ]
