# Generated by Django 4.0 on 2022-05-17 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_bank_account_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(1950), django.core.validators.MinValueValidator(2022)]),
        ),
    ]
