# Generated by Django 4.0 on 2022-05-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_jobexperience_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
